
INSERT INTO public.account_configs (account_id, account_name, handle, platform, vertical, monetization_mode, status, promise, posting_frequency_target, max_daily_posts, priority_score, persona, audience, content_pillars, allowed_product_categories, content_style)
VALUES
  ('privacy_minute', 'Privacy Minute', '@PrivacyMinute', 'tiktok', 'privacy', 'app_first', 'active',
   'Make digital privacy simple and actionable in 60 seconds',
   3, 4, 80,
   '{"tone": "authoritative", "vibe": "trustworthy"}'::jsonb,
   '{"who": "Privacy-conscious millennials", "pain_points": ["data tracking", "privacy breaches", "big tech surveillance"]}'::jsonb,
   ARRAY['privacy tips', 'data protection', 'app reviews', 'digital safety'],
   ARRAY[]::text[],
   'educational, clean, fast-paced'),

  ('digital_safety', 'Digital Safety Hacks', '@DigitalSafetyHQ', 'instagram', 'privacy', 'app_first', 'active',
   'Protect your digital life with practical hacks',
   2, 3, 60,
   '{"tone": "friendly", "vibe": "helpful"}'::jsonb,
   '{"who": "Non-technical adults worried about privacy", "pain_points": ["feeling exposed online", "not knowing what to do"]}'::jsonb,
   ARRAY['safety hacks', 'privacy settings', 'tool recommendations'],
   ARRAY[]::text[],
   'tutorial, step-by-step, reassuring'),

  ('health_insights', 'Health Insights Daily', '@HealthInsightsHQ', 'tiktok', 'health', 'app_first', 'active',
   'Evidence-based health insights you can use today',
   3, 4, 75,
   '{"tone": "authoritative", "vibe": "caring"}'::jsonb,
   '{"who": "Health-conscious adults 25-45", "pain_points": ["misinformation", "confusing health advice"]}'::jsonb,
   ARRAY['health tips', 'wellness', 'prevention', 'recovery'],
   ARRAY[]::text[],
   'educational, clean, trustworthy'),

  ('brain_recovery', 'Brain Recovery Tips', '@BrainRecoveryTips', 'instagram', 'health', 'app_first', 'warmup',
   'Support your brain health and recovery journey',
   2, 3, 55,
   '{"tone": "empathetic", "vibe": "supportive"}'::jsonb,
   '{"who": "Stroke survivors and caregivers", "pain_points": ["recovery uncertainty", "feeling alone"]}'::jsonb,
   ARRAY['stroke recovery', 'brain health', 'rehabilitation', 'cognitive exercises'],
   ARRAY[]::text[],
   'personal, warm, hopeful'),

  ('career_boost', 'Career Boost HQ', '@CareerBoostHQ', 'tiktok', 'education', 'app_first', 'active',
   'Accelerate your career with smart strategies',
   3, 4, 85,
   '{"tone": "motivational", "vibe": "energetic"}'::jsonb,
   '{"who": "Ambitious professionals 22-35", "pain_points": ["career stagnation", "interview anxiety", "skill gaps"]}'::jsonb,
   ARRAY['career tips', 'interview prep', 'resume advice', 'skill building'],
   ARRAY[]::text[],
   'fast-paced, punchy, motivational'),

  ('resume_pro', 'Resume Pro Tips', '@ResumeProTips', 'instagram', 'education', 'app_first', 'warmup',
   'Build resumes that actually get interviews',
   2, 3, 50,
   '{"tone": "practical", "vibe": "professional"}'::jsonb,
   '{"who": "Job seekers", "pain_points": ["resume rejections", "ATS confusion"]}'::jsonb,
   ARRAY['resume writing', 'cover letters', 'ATS optimization'],
   ARRAY[]::text[],
   'tutorial, clean, professional'),

  ('gadget_finds', 'Gadget Finds Daily', '@GadgetFindsDaily', 'tiktok', 'gadgets', 'product_first', 'active',
   'Discover the coolest gadgets you did not know existed',
   3, 5, 80,
   '{"tone": "excited", "vibe": "discovery"}'::jsonb,
   '{"who": "Tech-curious impulse buyers 18-35", "pain_points": ["missing cool products", "wasting money on bad gadgets"]}'::jsonb,
   ARRAY['gadget reviews', 'product demos', 'tech finds', 'unboxing'],
   ARRAY['gadgets', 'tech', 'electronics', 'accessories'],
   'demo-first, fast reveals, satisfying'),

  ('smart_under50', 'Smart Stuff Under $50', '@SmartUnder50', 'instagram', 'gadgets', 'product_first', 'active',
   'The best smart gadgets that wont break the bank',
   2, 3, 65,
   '{"tone": "value-focused", "vibe": "curated"}'::jsonb,
   '{"who": "Budget-conscious gadget lovers", "pain_points": ["overpaying", "finding quality at low price"]}'::jsonb,
   ARRAY['budget tech', 'value finds', 'price comparisons'],
   ARRAY['gadgets', 'tech', 'accessories'],
   'price-focused, comparison, value-driven'),

  ('home_glow', 'Home Glow Finds', '@HomeGlowFinds', 'tiktok', 'home', 'product_first', 'active',
   'Transform your space with stunning home finds',
   3, 4, 75,
   '{"tone": "aesthetic", "vibe": "aspirational"}'::jsonb,
   '{"who": "Home decor enthusiasts 22-40", "pain_points": ["boring spaces", "expensive decor"]}'::jsonb,
   ARRAY['home decor', 'ambient lighting', 'room transformation', 'aesthetic finds'],
   ARRAY['home', 'lighting', 'decor', 'furniture'],
   'aesthetic, satisfying, transformation-focused'),

  ('tiny_upgrades', 'Tiny Space Upgrades', '@TinySpaceUpgrades', 'instagram', 'home', 'product_first', 'warmup',
   'Small changes, big impact for your home',
   2, 3, 50,
   '{"tone": "practical", "vibe": "relatable"}'::jsonb,
   '{"who": "Apartment dwellers, renters", "pain_points": ["small spaces", "rental restrictions"]}'::jsonb,
   ARRAY['small space hacks', 'organization', 'affordable upgrades'],
   ARRAY['home', 'organization', 'storage', 'decor'],
   'problem-solution, before-after, practical'),

  ('toy_finds', 'Toy Finds Parents Love', '@ToyFindsParents', 'tiktok', 'toys', 'product_first', 'active',
   'Discover toys that kids love and parents approve',
   2, 3, 70,
   '{"tone": "enthusiastic", "vibe": "family-friendly"}'::jsonb,
   '{"who": "Parents of kids 3-12", "pain_points": ["screen time", "finding quality toys", "gift ideas"]}'::jsonb,
   ARRAY['educational toys', 'gift ideas', 'toy reviews', 'kids activities'],
   ARRAY['toys', 'kids', 'educational', 'games'],
   'demo-first, kid reactions, parent-approved'),

  ('oddly_satisfying_toys', 'Oddly Satisfying Toys', '@OddlySatisfyingToys', 'instagram', 'toys', 'product_first', 'warmup',
   'The most satisfying toys and fidgets on the internet',
   2, 3, 55,
   '{"tone": "playful", "vibe": "mesmerizing"}'::jsonb,
   '{"who": "Fidget/ASMR lovers, gift shoppers", "pain_points": ["stress relief", "boredom"]}'::jsonb,
   ARRAY['fidget toys', 'ASMR', 'satisfying videos', 'stress relief'],
   ARRAY['toys', 'fidgets', 'stress relief', 'novelty'],
   'visual, satisfying, loop-friendly')
ON CONFLICT (account_id) DO NOTHING;
