// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrujlpljluvxewjytuab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydWpscGxqbHV2eGV3anl0dWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDMwODYsImV4cCI6MjA2NjAxOTA4Nn0.SDAcfo63YiNToCSXzoHRGhEKC3hmtYdp_cPBdFDN0HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});